### ISSUE TITLE
TypeError: softmax() got an unexpected keyword argument 'dim'

### ISSUE THREAD

**Issue by Deephome** [AlexHex7/Non-local_pytorch#2]
Hello！ when I run the code， I got an error  ''TypeError: softmax() got an unexpected keyword argument 'dim'  '' in non_local_simple version.py ( line 77 : f_div_C = F.softmax(f, dim=-1) ). Can you give me some advice? thanks!

**Comment by AlexHex7** [comment]
Hi, the old version of pytorch didn't has 'dim' argument, for example pytorch 0.2. When writing this code, I used pytorch 0.3. You can try to update the pytorch to 0.4, it works too.
