### ISSUE TITLE
Can you give experiment result of this code?

### ISSUE THREAD

**Issue by Woolseyyy** [AlexHex7/Non-local_pytorch#29]
Thank you for your work!
Can you give the result of experiment on MNIST to check?

**Comment by AlexHex7** [comment]
Hi @Woolseyyy. My Repo is just a demo showing how to use Non-local Module (https://github.com/AlexHex7/Non-local_pytorch/issues/31#issuecomment-549652707), so maybe it works not significantly well on MNIST dataset.

My experiment result is shown as follow

> (LR:0.001000) Time of a epoch:78.0753s
> [Test] epoch[0/100] acc:98.5700% loss:0.0430
> 
> (LR:0.001000) Time of a epoch:33.8620s
> [Test] epoch[1/100] acc:99.0700% loss:0.0294
> 
> (LR:0.001000) Time of a epoch:41.6577s
> [Test] epoch[2/100] acc:99.2000% loss:0.0249
> 
> (LR:0.001000) Time of a epoch:46.2476s
> [Test] epoch[3/100] acc:98.7000% loss:0.0416
> 
> (LR:0.001000) Time of a epoch:45.1013s
> [Test] epoch[4/100] acc:98.9900% loss:0.0338
> 
> (LR:0.001000) Time of a epoch:35.7351s
> [Test] epoch[5/100] acc:99.0000% loss:0.0296
> 
> (LR:0.001000) Time of a epoch:41.4202s
> [Test] epoch[6/100] acc:99.4300% loss:0.0201
> 
> (LR:0.001000) Time of a epoch:38.3029s
> [Test] epoch[7/100] acc:99.4100% loss:0.0207
> 
> (LR:0.001000) Time of a epoch:37.4420s
> [Test] epoch[8/100] acc:99.1900% loss:0.0275
> 
> (LR:0.001000) Time of a epoch:44.3929s
> [Test] epoch[9/100] acc:99.2600% loss:0.0258
> 
> (LR:0.001000) Time of a epoch:44.4165s
> [Test] epoch[10/100] acc:99.1500% loss:0.0284
> 
> (LR:0.001000) Time of a epoch:33.3943s
> [Test] epoch[11/100] acc:99.3700% loss:0.0237
>

**Comment by Woolseyyy** [comment]
Thank you!
