### ISSUE TITLE
How about NotImplementedError('Mode concatenation has not been implemented.')

### ISSUE THREAD

**Issue by PkuRainBow** [AlexHex7/Non-local_pytorch#3]
Great repo.

I am wondering when it is possible to provide the implementation for the "concatenation" operator~

**Comment by AlexHex7** [comment]
Hi, I have provided the implementation of "concatenation" operator.
Sorry for replying so late. I'm so busy these days. And when someone opens an issue, I can't receive notifications, I don't know how to set it.
