### ISSUE TITLE
accuracy of the test

### ISSUE THREAD

**Issue by MASTERCHIEF343** [AlexHex7/Non-local_pytorch#31]
Hi, thank you for your code.I think is great. But I have some problems.When I delete Non-local module.I find that the accuracy of test will go higher.I'll test again.Have you ever met that ?

**Comment by jjy91234** [comment]
hi,I found the same problem, how do you solve it?

**Comment by MASTERCHIEF343** [comment]
> hi,I found the same problem, how do you solve it?

Actually I don't know.As for me, I think this method can help the net to know the similarity between each pixels, so it's good for segmentation or just like in FlowNet, we use correlation layer to learn the relationship between different pixels.But in this MNIST demo, I think it won't help us learn better about  the classification because we have already learned  enough features for classification.I just want to use the same ideology for depth estimation, because it will learn  the difference for different depth plane.That's all I think.

**Comment by AlexHex7** [comment]
@MASTERCHIEF343 @jjy91234 Hi. I agree with MASTERCHIEF343. Perhaps the image size is relatively small than real-world images', even the regular Conv can achieve enough perceptive filed. And my Repo is just a demo showing how to use Non-local Module.

On the other hand, I tried to apply Non-local Module to a Biomedical Image Task, There was no improvement in my experiments. But on some datasets, it really works. So I think that to some extent, it has something to do with the dataset type.

**Comment by jjy91234** [comment]
@MASTERCHIEF343 @AlexHex7 I think your reply is right.The MNIST task is so simple that the original net is enough.But it is helpful to segmentation task. Thank you very much!

**Comment by MASTERCHIEF343** [comment]
@jjy91234 You're welcome!Maybe in other problems it will work.But also, non-local module takes much time, So maybe you can see some papers just like CCNet which can reduce the computation.
