### ISSUE TITLE
Resnet version

### ISSUE THREAD

**Issue by Youngkl0726** [AlexHex7/Non-local_pytorch#6]
Hi,
   Did you try to add the non-local block into Resnet model？

**Comment by guangmingboy** [comment]
Out of memory.

**Comment by AlexHex7** [comment]
I have not try to add it into ResNet. The non-local operation contains matrix multiplication, it takes lots of  memories. So it should be added into high-level blocks (it is also mentioned in the paper), or you can try to reduce batch size.

**Comment by AlexHex7** [comment]
@Youngkl0726 What's your dataset? your code looks like focus on 2D classifition. And the paper reports video classification, instance segmentation and detection, maybe the normal model already does well on your dataset.

**Comment by Youngkl0726** [comment]
ImageNet. The paper said, We modify the Mask R-CNN backbone by adding one non-local block (right before the last residual block of res4). I thought this modification may bring an improvement of the backbone, so I added a non-local block into Resnet50 to train ImageNet.

**Comment by AlexHex7** [comment]
Uh... I have do the experiments of the paper, but I use it in some experiments, it really works. But it does not works on other experiments too.

**Comment by Youngkl0726** [comment]
I used it in some experiments, but it didn't work at all. How did you use it in your experiments?

**Comment by AlexHex7** [comment]
Sorry for replying so late. I use it in my own experiments and I still do the research now.
